# Generated by Django 4.2.7 on 2024-03-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iek5', '0108_remove_doenerorder_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafer',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='current_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='dimension',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='ingot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ingot Number'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='lifetime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lifetime according to manufacturer in ms'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Identification'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='np',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='n/p Type'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of Wafers Delivered'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='orientation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='resistivity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resistivity according to manufacturer in Ωcm'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='surface',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Surface Structure'),
        ),
        migrations.AlterField(
            model_name='wafer',
            name='thickness',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Thickness according to manufacturer in µm'),
        ),
    ]
