# Generated by Django 1.9.6 on 2016-08-19 17:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jb_common', '0002_language_default_en'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('name', 'department', 'parent_topic')]),
        ),
    ]
