# Generated by Django 3.2.10 on 2022-01-18 13:25

from django.db import migrations
import jb_common.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_sorted_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustertooldeposition',
            name='carrier',
            field=jb_common.model_fields.CharField(blank=True, max_length=10, verbose_name='carrier'),
        ),
        migrations.AlterField(
            model_name='clustertoolhotwirelayer',
            name='comments',
            field=jb_common.model_fields.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='clustertoolhotwirelayer',
            name='time',
            field=jb_common.model_fields.CharField(blank=True, help_text='format HH:MM:SS', max_length=9, verbose_name='deposition time'),
        ),
        migrations.AlterField(
            model_name='clustertoolhotwirelayer',
            name='wire_material',
            field=jb_common.model_fields.CharField(choices=[('unknown', 'unknown'), ('rhenium', 'rhenium'), ('tantalum', 'tantalum'), ('tungsten', 'tungsten')], max_length=20, verbose_name='wire material'),
        ),
        migrations.AlterField(
            model_name='clustertoollayer',
            name='number',
            field=jb_common.model_fields.PositiveIntegerField(verbose_name='layer number'),
        ),
        migrations.AlterField(
            model_name='clustertoolpecvdlayer',
            name='chamber',
            field=jb_common.model_fields.CharField(choices=[('#1', '#1'), ('#2', '#2'), ('#3', '#3')], max_length=5, verbose_name='chamber'),
        ),
        migrations.AlterField(
            model_name='clustertoolpecvdlayer',
            name='comments',
            field=jb_common.model_fields.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='clustertoolpecvdlayer',
            name='plasma_start_with_shutter',
            field=jb_common.model_fields.BooleanField(default=False, verbose_name='plasma start with shutter'),
        ),
        migrations.AlterField(
            model_name='clustertoolpecvdlayer',
            name='time',
            field=jb_common.model_fields.CharField(blank=True, help_text='format HH:MM:SS', max_length=9, verbose_name='deposition time'),
        ),
        migrations.AlterField(
            model_name='fivechamberlayer',
            name='chamber',
            field=jb_common.model_fields.CharField(choices=[('i1', 'i1'), ('i2', 'i2'), ('i3', 'i3'), ('p', 'p'), ('n', 'n')], max_length=2, verbose_name='chamber'),
        ),
        migrations.AlterField(
            model_name='fivechamberlayer',
            name='layer_type',
            field=jb_common.model_fields.CharField(blank=True, choices=[('p', 'p'), ('i', 'i'), ('n', 'n')], max_length=2, verbose_name='layer type'),
        ),
        migrations.AlterField(
            model_name='fivechamberlayer',
            name='number',
            field=jb_common.model_fields.PositiveIntegerField(verbose_name='layer number'),
        ),
        migrations.AlterField(
            model_name='layerthicknessmeasurement',
            name='method',
            field=jb_common.model_fields.CharField(choices=[('profilers&edge', 'profilometer + edge'), ('ellipsometer', 'ellipsometer'), ('calculated', 'calculated from deposition parameters'), ('estimate', 'estimate'), ('other', 'other')], default='profilers&edge', max_length=30, verbose_name='measurement method'),
        ),
        migrations.AlterField(
            model_name='pdsmeasurement',
            name='apparatus',
            field=jb_common.model_fields.CharField(choices=[('pds1', 'PDS #1'), ('pds2', 'PDS #2')], default='pds1', max_length=15, verbose_name='apparatus'),
        ),
        migrations.AlterField(
            model_name='pdsmeasurement',
            name='number',
            field=jb_common.model_fields.PositiveIntegerField(db_index=True, unique=True, verbose_name='PDS number'),
        ),
        migrations.AlterField(
            model_name='pdsmeasurement',
            name='raw_datafile',
            field=jb_common.model_fields.CharField(help_text='only the relative path below "pds_raw_data/"', max_length=200, verbose_name='raw data file'),
        ),
        migrations.AlterField(
            model_name='solarsimulatorcellmeasurement',
            name='data_file',
            field=jb_common.model_fields.CharField(db_index=True, help_text='only the relative path below "solarsimulator_raw_data/"', max_length=200, verbose_name='data file'),
        ),
        migrations.AlterField(
            model_name='solarsimulatorcellmeasurement',
            name='position',
            field=jb_common.model_fields.CharField(max_length=5, verbose_name='cell position'),
        ),
        migrations.AlterField(
            model_name='solarsimulatormeasurement',
            name='irradiation',
            field=jb_common.model_fields.CharField(choices=[('AM1.5', 'AM1.5'), ('OG590', 'OG590'), ('BG7', 'BG7')], max_length=10, verbose_name='irradiation'),
        ),
        migrations.AlterField(
            model_name='structuring',
            name='layout',
            field=jb_common.model_fields.CharField(choices=[('inm standard', 'INM Standard'), ('acme1', 'ACME 1'), ('custom', 'custom')], max_length=30, verbose_name='layout'),
        ),
        migrations.AlterField(
            model_name='structuring',
            name='parameters',
            field=jb_common.model_fields.TextField(blank=True, verbose_name='parameters'),
        ),
        migrations.AlterField(
            model_name='substrate',
            name='material',
            field=jb_common.model_fields.CharField(choices=[('custom', 'custom'), ('asahi-u', 'ASAHI-U'), ('asahi-vu', 'ASAHI-VU'), ('corning', 'Corning glass'), ('glass', 'glass'), ('si-wafer', 'silicon wafer'), ('quartz', 'quartz'), ('sapphire', 'sapphire'), ('aluminium foil', 'aluminium foil')], max_length=30, verbose_name='substrate material'),
        ),
    ]
