# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_feeddeletedsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDeletedProcess',
            fields=[
                ('feedentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.FeedEntry')),
                ('process_name', models.TextField(verbose_name='process name')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'deleted process feed entry',
                'verbose_name_plural': 'deleted process feed entries',
            },
            bases=('samples.feedentry',),
        ),
    ]
