# Generated by Django 3.1.1 on 2020-09-01 12:57

from django.db import migrations, models
import samples.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_auto_20200902_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='quantities_and_values',
            field=models.JSONField(blank=True, default=samples.models.common.empty_double_list, verbose_name='quantities and values'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='folded_processes',
            field=models.JSONField(blank=True, default=samples.models.common.empty_dict, verbose_name='folded processes'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='folded_series',
            field=models.JSONField(blank=True, default=samples.models.common.empty_list, verbose_name='folded sample series'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='folded_topics',
            field=models.JSONField(blank=True, default=samples.models.common.empty_list, verbose_name='folded topics'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='my_steps',
            field=models.JSONField(blank=True, default=samples.models.common.empty_list, verbose_name='My Steps'),
        ),
    ]
