# Generated by Django 4.2.13 on 2025-01-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0009_auto_20200901_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='last_modified_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier'),
        ),
    ]
