# Generated by Django 3.2.7 on 2021-10-15 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalData',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('url', models.URLField(verbose_name='URL')),
                ('login', models.CharField(max_length=2048, verbose_name='login name')),
            ],
            options={
                'verbose_name': 'external data',
                'verbose_name_plural': 'external data',
                'abstract': False,
            },
            bases=('samples.process',),
        ),
    ]
