# Generated by Django 4.0.10 on 2023-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20200901_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='air_sensitive',
            field=models.BooleanField(default=False, verbose_name='air sensitive'),
        ),
        migrations.AddField(
            model_name='task',
            name='biohazard1',
            field=models.BooleanField(default=False, verbose_name='biohazard BSL-1'),
        ),
        migrations.AddField(
            model_name='task',
            name='chilled',
            field=models.BooleanField(default=False, verbose_name='chilled'),
        ),
        migrations.AddField(
            model_name='task',
            name='deep_frozen',
            field=models.BooleanField(default=False, verbose_name='deep-frozen'),
        ),
        migrations.AddField(
            model_name='task',
            name='explosive',
            field=models.BooleanField(default=False, verbose_name='explosive'),
        ),
        migrations.AddField(
            model_name='task',
            name='inflammable',
            field=models.BooleanField(default=False, verbose_name='inflammable'),
        ),
        migrations.AddField(
            model_name='task',
            name='innocuous',
            field=models.BooleanField(default=True, verbose_name='innocuous'),
        ),
        migrations.AddField(
            model_name='task',
            name='light_sensitive',
            field=models.BooleanField(default=False, verbose_name='light sensitive'),
        ),
        migrations.AddField(
            model_name='task',
            name='moisture_sensitive',
            field=models.BooleanField(default=False, verbose_name='moisture sensitive'),
        ),
        migrations.AddField(
            model_name='task',
            name='radioactive',
            field=models.BooleanField(default=False, verbose_name='radioactive'),
        ),
        migrations.AddField(
            model_name='task',
            name='toxic',
            field=models.BooleanField(default=False, verbose_name='toxic'),
        ),
    ]
