# Generated by Django 3.2.10 on 2022-01-18 13:25

from django.db import migrations
import jb_common.model_fields
import samples.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0010_externaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='last_modified',
            field=jb_common.model_fields.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='deposition',
            name='number',
            field=jb_common.model_fields.CharField(db_index=True, max_length=15, unique=True, verbose_name='deposition number'),
        ),
        migrations.AlterField(
            model_name='deposition',
            name='split_done',
            field=jb_common.model_fields.BooleanField(default=False, verbose_name='split after deposition done'),
        ),
        migrations.AlterField(
            model_name='externaldata',
            name='url',
            field=jb_common.model_fields.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='process',
            name='comments',
            field=jb_common.model_fields.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='process',
            name='finished',
            field=jb_common.model_fields.BooleanField(default=True, verbose_name='finished'),
        ),
        migrations.AlterField(
            model_name='process',
            name='last_modified',
            field=jb_common.model_fields.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='process',
            name='timestamp',
            field=jb_common.model_fields.DateTimeField(verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='process',
            name='timestamp_inaccuracy',
            field=jb_common.model_fields.PositiveSmallIntegerField(choices=[(0, 'totally accurate'), (1, 'accurate to the minute'), (2, 'accurate to the hour'), (3, 'accurate to the day'), (4, 'accurate to the month'), (5, 'accurate to the year'), (6, 'not even accurate to the year')], default=0, verbose_name='timestamp inaccuracy'),
        ),
        migrations.AlterField(
            model_name='result',
            name='image_type',
            field=jb_common.model_fields.CharField(choices=[('none', 'none'), ('pdf', 'PDF'), ('png', 'PNG'), ('jpeg', 'JPEG')], default='none', max_length=4, verbose_name='image file type'),
        ),
        migrations.AlterField(
            model_name='result',
            name='quantities_and_values',
            field=jb_common.model_fields.JSONField(blank=True, default=samples.models.common.empty_double_list, verbose_name='quantities and values'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=jb_common.model_fields.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='current_location',
            field=jb_common.model_fields.CharField(max_length=50, verbose_name='current location'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='last_modified',
            field=jb_common.model_fields.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=jb_common.model_fields.CharField(db_index=True, max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='purpose',
            field=jb_common.model_fields.CharField(blank=True, max_length=80, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='tags',
            field=jb_common.model_fields.CharField(blank=True, help_text='separated with commas, no whitespace', max_length=255, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='samplealias',
            name='name',
            field=jb_common.model_fields.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sampleclaim',
            name='closed',
            field=jb_common.model_fields.BooleanField(default=False, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='sampledeath',
            name='reason',
            field=jb_common.model_fields.CharField(choices=[('split', 'completely split'), ('lost', 'lost and unfindable'), ('destroyed', 'completely destroyed')], max_length=50, verbose_name='cause of death'),
        ),
        migrations.AlterField(
            model_name='sampleseries',
            name='description',
            field=jb_common.model_fields.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sampleseries',
            name='last_modified',
            field=jb_common.model_fields.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='sampleseries',
            name='name',
            field=jb_common.model_fields.CharField(help_text='must be of the form “originator-YY-name”', max_length=50, primary_key=True, serialize=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sampleseries',
            name='timestamp',
            field=jb_common.model_fields.DateTimeField(verbose_name='timestamp'),
        ),
    ]
