# Generated by Django 5.2.7 on 2026-05-11 08:23

import django.db.models.deletion
import jb_common.model_fields
import samples.models.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_sample_external_graph_urls_delete_externaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalData',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='samples.process')),
                ('title', jb_common.model_fields.CharField(max_length=50, verbose_name='title')),
                ('uri', jb_common.model_fields.URLField(verbose_name='URI')),
                ('keys_and_values', jb_common.model_fields.JSONField(blank=True, default=samples.models.common.empty_dict, verbose_name='keys and values')),
            ],
            options={
                'verbose_name': 'external data',
                'verbose_name_plural': 'external data',
                'abstract': False,
                'managed': False,
            },
            bases=('samples.process',),
        ),
    ]
